name: kind_uuid
version: 1.0.1
description: A performant UUID implementation that supports the two common UUID
  versions (1 and 4) and two IETF standard drafts (6 and 7).
homepage: https://github.com/dint-dev/kind_uuid

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  clock: ^1.1.0
  collection: ^1.16.0
  meta: ^1.8.0

dev_dependencies:
  benchmark_harness: ^2.2.0
  lints: ^2.0.0
  test: ^1.21.5
